--1
SELECT COUNT(*) as NUMERO_EMPLEADOS
FROM [dbo].[EMPLEADO$];

--2
SELECT COUNT(*) as EMPLEADOS_SEDE_NORTE
FROM [dbo].[EMPLEADO$]
WHERE [FK_SEDE] = 1;

SELECT COUNT(*) as EMPLEADOS_SEDE_CENTRO
FROM [dbo].[EMPLEADO$]
WHERE [FK_SEDE] = 2;

SELECT COUNT(*) as EMPLEADOS_SEDE_SUR
FROM [dbo].[EMPLEADO$]
WHERE [FK_SEDE] = 3;

SELECT COUNT(*) as EMPLEADOS_SEDE_OCCIDENTE
FROM [dbo].[EMPLEADO$]
WHERE [FK_SEDE] = 4;

SELECT COUNT(*) as EMPLEADOS_SEDE_ORIENTE
FROM [dbo].[EMPLEADO$]
WHERE [FK_SEDE] = 5;

--3
SELECT COUNT(*) as EMPLEADOS_ESTRATO1
FROM [dbo].[EMPLEADO$]
WHERE [FK_ESTRATO] = 1

SELECT COUNT(*) as EMPLEADOS_ESTRATO2
FROM [dbo].[EMPLEADO$]
WHERE [FK_ESTRATO] = 2

SELECT COUNT(*) as EMPLEADOS_ESTRATO3
FROM [dbo].[EMPLEADO$]
WHERE [FK_ESTRATO] = 3

SELECT COUNT(*) as EMPLEADOS_ESTRATO4
FROM [dbo].[EMPLEADO$]
WHERE [FK_ESTRATO] = 4


SELECT COUNT(*) as EMPLEADOS_ESTRATO5
FROM [dbo].[EMPLEADO$]
WHERE [FK_ESTRATO] = 5

SELECT COUNT(*) as EMPLEADOS_ESTRATO6
FROM [dbo].[EMPLEADO$]
WHERE [FK_ESTRATO] = 6

--4
SELECT *
FROM [dbo].[EMPLEADO$]
WHERE [fecha_de_contratacion] = (
	SELECT MAX([fecha_de_contratacion])
	FROM[dbo].[EMPLEADO$]
	);

--5
SELECT *
FROM [dbo].[EMPLEADO$]
WHERE [fecha_de_contratacion] = (
	SELECT MIN([fecha_de_contratacion])
	FROM[dbo].[EMPLEADO$]
	);

--6
SELECT [nombres], [primer_apellido], [segundo_apellido]
FROM [dbo].[EMPLEADO$]
WHERE [cc] = 10662101;

SELECT [sede] AS s
FROM [dbo].[SEDE$]
LEFT JOIN [dbo].[EMPLEADO$] as e
ON e.cc = 
WHERE 

--7 
DELETE FROM [dbo].[EMPLEADO$]
WHERE [cc] = 10188530;
